### PR TITLE
Fix for latest iTerm AppleScript API

### LINKED ISSUE #2: Tab not opened in iTerm
Running `tab` (or with any options) does not open a new tab and instead causes an error code to be returned.

iTerm2 Build: 2.9.20150830
Fish Version: 2.2.0

### PR DESCRIPTION
**Pull request by dan-c-underwood**
Plugin should now work for versions of iTerm > 2.9.20150414.

This should fix #2.

### CODE REVIEW

**Comment by bpinto** [comment]
What about versions before 2.9?

**Comment by dan-c-underwood** [comment]
But it's way more fun just supporting beta versions of software! This method, using a fallback, seems to work (tested on iTerm 2.2 and 2.9) but is a bit ugly (although cleaner than trying to access the iTerm build number from the command line I think!)

**Comment by bobthecow** [comment]
I'm okay with ugly fallback for now. Since 2.9 is still beta I'd switch the order, though. Also looks like there's something funny with white space?

**Comment by dan-c-underwood** [comment]
Looks like the whitespace got messed up when going from Script Editor into Atom 😑

Order is now switched.

**Comment by bpinto** [comment]
LGTM.

**Comment by bobthecow** [comment]
Thanks!

**Pull request merged**
